### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by crazy-max** [portapps/portapps.github.io#1]
* portapps/discord-portable#3
* portapps/discord-portable#7
* portapps/docker-toolbox-portable#1
* portapps/intellij-idea-ultimate-portable#1
* portapps/skype-portable#4
* portapps/brave-portable#2
* portapps/postman-portable#1
* portapps/twitch-portable#2
* portapps/portapps#1

**Comment by RoyiAvital** [comment]
Hi,

You should add section for "Request for Applications".

I'd be happy to see:

- [CodeBlocks](http://www.codeblocks.org/).
- [CLion](https://www.jetbrains.com/clion/).
- [Octave](https://www.gnu.org/software/octave/).

Thank You.

**Comment by crazy-max** [comment]
Hi @RoyiAvital, good suggestion. Can you post separate issues [here](https://github.com/portapps/portapps/issues) for each app requests ? Thanks

**Comment by crazy-max** [comment]
@RoyiAvital An [App request page](https://portapps.github.io/doc/) has been added to the documentation.
