### ISSUE TITLE
Wrong count of Portapps

### ISSUE THREAD

**Issue by angelog0** [portapps/portapps.github.io#10]
This [page](https://portapps.io/apps) say:

`The Portapps catalog contains a growing list of 48 applications.`

but counting them shows 47 icons (a grid 3*15 + 2).

Which is missing?

**Comment by crazy-max** [comment]
@angelog0 You didn't miss anything, it's a miscount :)

**Comment by crazy-max** [comment]
Should be fixed now, thanks for your input.
