### ISSUE TITLE
typos (?) in src/_pages/doc/configuration.md

### ISSUE THREAD

**Issue by maelcum** [portapps/portapps.github.io#53]
Hi,

I am not a developer, sorry if the following sounds crazy:

The example on the page portapps/portapps.github.io/src/_pages/doc/configuration.md starts like this:
```
common:
  args:
    - --debug
    - --key=value
```

using that syntax does not work for me. instead, this works:
```
common:
  args:
    --debug,
    --key=value
```

- no leading '-' in front of each line of argument, and 
- a comma/semicolon after each argument except for the last.

could this be a typo?

**Comment by crazy-max** [comment]
@maelcum 

> could this be a typo?

Not a typo

> ```yaml
> common:
>   args:
>     - --debug
>     - --key=value
> ```

The YAML config example is valid (https://codebeautify.org/yaml-validator/cbab7e76) and will append `--debug --key=value` to the launch command of the portable app. If that's not your case, please open issue on the affected portable app. Thanks.

Your configuration is not: https://codebeautify.org/yaml-validator/cb4dfcc4

**Comment by maelcum** [comment]
thanks! and sorry!
