### ISSUE TITLE
Wrong profil path ?

### ISSUE THREAD

**Issue by Johann999** [portapps/portapps.github.io#8]
#### Steps to reproduce this issue

1. install  brave portable 0.66.101-26 32-Bit on Windows 10 32-bit and 64-bit
2.
3.

#### Expected behaviour
the profile path should be C:\Programme\brave-portable\data\Default (32-bit)
and C:\Programme (x86)\brave-portable\data\Default (64-bit)

#### Actual behaviour
on Windows 32-bit the profile path  is C:\Programme\brave-portable\data (correct)

on Windows 64-bit the profile path is C:\Users\[user]\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
why?

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
 brave portable 0.66.101-26

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 OS Build 17763.195
Windows 10 Pro 32-bit and Windows 10 Pro 64-bit
**Winver screenshot** :
Microsoft Windows [Version 10.0.17763.195]

### Screenshots
Windows 32-bit:
Ausführbarer Pfad   C:\Program Files\brave-portable\app\brave.exe
Profilpfad     C:\Program Files\brave-portable\data\Default

Windows 64-bit:
Ausführbarer Pfad	C:\Program Files (x86)\brave-portable\app\brave.exe
Profilpfad	C:\Users\irc\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

### Logs

on Windows 64-bit there ist no log-file.

**Comment by crazy-max** [comment]
Please open an issue on the right repo : https://github.com/portapps/brave-portable
